### ISSUE TITLE
Travis build is broken

### ISSUE THREAD

**Issue by mmarchini** [jdewit/bootstrap-timepicker#269]
Travis build isn't working. Looks like it's a problem with the npm version used by them.

``` npm
npm ERR! Error: No compatible version found: glob@'^4.3.2'
npm ERR! Valid install targets:
npm ERR! ["1.1.0","2.0.9","2.0.8","2.0.7","2.1.0","3.0.0","3.0.1","3.1.0","3.1.1","3.1.2","3.1.3","3.1.4","3.1.5","3.1.6","3.1.7","3.1.9","3.1.10","3.1.11","3.1.12","3.1.13","3.1.14","3.1.15","3.1.16","3.1.17","3.1.18","3.1.19","3.1.20","3.1.21","3.2.0","3.2.1","3.2.3","3.2.4","3.2.5","3.2.6","3.2.7","3.2.8","3.2.9","3.2.10","3.2.11","4.0.0","4.0.1","4.0.2","4.0.3","4.0.4","4.0.5","4.0.6","4.1.2-beta","4.1.2","4.1.3","4.1.4","4.1.5","4.1.6","4.2.0","4.2.1","4.2.2","4.3.0","4.3.1","4.3.2","4.3.3","4.3.4","4.3.5","4.4.0","4.4.2","4.5.0","5.0.0","4.5.1","5.0.1","4.5.2","5.0.2","4.5.3","5.0.3","5.0.4","5.0.5","5.0.6","5.0.7","5.0.9","5.0.10","5.0.11","5.0.12","5.0.13","5.0.14"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at RegClient.get_ (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:101:14)
npm ERR!     at RegClient.<anonymous> (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:37:12)
npm ERR!     at fs.readFile (fs.js:181:14)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! System Linux 2.6.32-042stab108.5
npm ERR! command "/home/travis/.nvm/v0.8.28/bin/node" "/home/travis/.nvm/v0.8.28/bin/npm" "install"
npm ERR! cwd /home/travis/build/jdewit/bootstrap-timepicker
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
```

Older versions of npm doesn't have the `^` semver operator (https://github.com/npm/npm/issues/7882#issuecomment-90943463), which is used by some dependencies.

**Comment by mrhota** [comment]
updating `.travis.yml` in #270 seemed to do the trick.
